### ISSUE TITLE
Undefined symbols for architecture x86_64

### ISSUE THREAD

**Issue by ilyasdogruer** [moip/ios-sdk-sample#3]
Hi,

When i try to run the sample app on Xcode 6.2, i get the errors like in the screenshot. How can i fix this?
![moip_ios_errors](https://cloud.githubusercontent.com/assets/366514/7093152/6f9404fe-dfbf-11e4-9d99-30c1de0f92a7.png)

**Comment by fnazarios** [comment]
Hi,

I cannot reproduce this error message.

Get the new version and test again.

**Comment by ilyasdogruer** [comment]
You've replaced the moip framework, its not giving errors now. But how can we create an order with this framework? The following methods of the SDK, are not included.

+ (MoipSDK *) startSessionWithToken:(NSString *)token
                                key:(NSString *)key
                          publicKey:(NSString *)publicKey
                        environment:(MPKEnvironment)env;

- (void) createOrder:(NSURLRequest *)request
               order:(MPKOrder *)order
             success:(void (^)(MPKOrder *order, NSString *moipOrderId))success
             failure:(void (^)(NSArray *errorList))failure;

- (void) submitPayment:(MPKPayment *)payment
               success:(void (^)(MPKPaymentTransaction *transaction))success
               failure:(void (^)(NSArray *errorList))failure;

**Comment by fnazarios** [comment]
For now, we discontinued this SDK version. Download the new version and integrate your app using Moip API. 

Enviado do meu iPhone

**Comment by ilyasdogruer** [comment]
For now, we can not create an order and submit payment to Moip, right? If yes, when will you complete the SDK with submit payment feature?

Thanks.
